try:
    pass
except:
    pass
else:
    print("No exception")
finally:
    pass
